### ISSUE TITLE
ubuntu16.04 sudo node ble-simulator.js 错误

### ISSUE THREAD

**Issue by wohaoa** [luluxie/weixin-iot#1]
`module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/iking/wearable/weixin-iot-master/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
`

**Comment by wohaoa** [comment]
开发环境环境更新到和作者相同问题解决
